import OnThisPage from "@/components/layout/OnThisPage";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: " about | &ri.porto",
  description: "Generated by create next app",
};
export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="w-full max-w-[1440px] mx-3 grid grid-cols-12 gap-3">
      {children}
      <OnThisPage />
    </section>
  );
}
