import type { Metadata } from "next";
export const metadata: Metadata = {
  title: " &ri.blog",
  description: "Generated by create next app",
};
export default function BlogLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section
      id="blog"
      className="w-full max-w-[1440px] mx-3  grid grid-cols-12 gap-3 max-md:p-0"
    >
      {children}
    </section>
  );
}
